#!/bin/bash

if [ "$1" == "" ]; then
	print "No wallpaper provided."
elif [ "$1" == "--random" ]; then
	# Set the path to the wallpapers directory
	wallpapersDir="$HOME/Pictures/Wallpapers"

	# Get a list of all image files in the wallpapers directory
	wallpapers=("$wallpapersDir"/*)

	# Check if the wallpapers array is empty
	if [ ${#wallpapers[@]} -eq 0 ]; then
		# If the array is empty, refill it with the image files
		wallpapers=("$wallpapersDir"/*)
	fi

	# Select a random wallpaper from the array
	wallpaperIndex=$(( RANDOM % ${#wallpapers[@]} ))
		selectedWallpaper="${wallpapers[$wallpaperIndex]}"

	# Update the wallpaper using the swww img command
	swww img "$selectedWallpaper"

	# Remove the selected wallpaper from the array
	unset "wallpapers[$wallpaperIndex]"
else
	swww img "$1"
fi
